### ISSUE TITLE
Melhorar esquema Firebase

### ISSUE THREAD

**Issue by nayara** [Enegrecer/enegrecer-web#273]
hoje em dia estamos registrando 'Denúncia' em um nó separado das demais características da denúncia no banco de dados. Para melhorar a performance e o design do código seria melhor que todas as informações da denúncia estivesse no mesmo nó que a denúncia.

**Comment by srmeneses** [comment]
De fato a estrutura de dados fica mais intuitiva e melhor categorizável.
O que vocês acham de retirar o label de Agressão das chaves e colocá-los dentro de um objeto chamado "agressao"? 
Assim todas os dados serão acessados com a mesma padronização.

```yaml
{
  "agressao": {
    "bairro": "",
    "cidade": "",
    "data": "",
    "descricao": "",
    "endereco": "",
    "estado": "",
    "periodo": "",
    "categoriaCrime": "",
    "numeroBoletim": "",
    "numeroProcesso": "",
    "orgao": ""
  },
  "denunciante": {
    "nome": "",
    "dataNascimento": "",
    "cidade": "",
    "genero": "",
    "raca": "",
    "email": "",
    "telefone": "",
  },
  "vitima": {
    "nome": "",
    "dataNascimento": "",
    "cidade": "",
    "genero": "",
    "raca": "",
    "souAVitima": "",
    "email": "",
    "telefone": "",
  },
  "agressor": {
    "nome": "",
    "dataNascimento": "",
    "cidade": "",
    "estado": "",
    "bairro": "",
    "genero": "",
    "raca": "",
    "souAVitima": "",
    "email": "",
    "telefone": "",
    "descricao": ""
  }
}
```
